### ISSUE TITLE
Image pop out functionality

### ISSUE THREAD

**Issue by benseverett** [arctheowl/snezhi-portfolio#10]
Is it possible to zoom the image while the image is "popped out" from the image slider? This is important for technical drawings.

**Comment by benseverett** [comment]
Also, some of the images looks small when popped out, especially when I have the page fullscreen (I have a widescreen). Can image be some percentage of the screen size (80%?) so they grow when you fullscreen the window, but no larger than their maximum size as we don't want pixerlated images.

**Comment by arctheowl** [comment]
Images can now be zoomed in once popped out, it does open them in another tab but it's the only way of doing it quickly. "eec443b..7b2c6dd" - "Added zoom in on technical images"
