### ISSUE TITLE
Black boxes colour

### ISSUE THREAD

**Issue by benseverett** [arctheowl/snezhi-portfolio#11]
Change colour of black boxes to grey or blue from portfolio

(hex code to follow)

**Comment by benseverett** [comment]
@SNVes Please provide the colour you'd want these boxe to be (RGBA / hex code)

**Comment by SNVes** [comment]
Could we try:
Grey RGB 241;241;241 (f1f1f1)
OR
Blue RGB 44;161;191 (2ca1bf)
