### ISSUE TITLE
Case Study Summaries

### ISSUE THREAD

**Issue by benseverett** [arctheowl/snezhi-portfolio#15]
Are the case study (projects) summaries rendered anywhere?

**Comment by arctheowl** [comment]
Yes they are in the work page they will appear under the title, can be removed or replaced with a section of the description if you'd rather.

**Comment by benseverett** [comment]
Aha yeah I see them now you got the "word" link working.

@SNVes linking back to what I asked earlier, what would you like to do with this page?

**Comment by benseverett** [comment]
Edit link for "work" to link back to the front page.
