### ISSUE TITLE
Default order of projects on main page

### ISSUE THREAD

**Issue by benseverett** [arctheowl/snezhi-portfolio#17]
What is the default order of projects on the main page? Is it possible to change it?

**Comment by arctheowl** [comment]
It's alphabetical, but it would be possible to change. I would have to add a priority to each project, so if you add a new category in the page.mdx file with a number in the order you want them to appear in it will make it easier for me to implement.

**Comment by benseverett** [comment]
It doesn't look alphabetical that's whats weird:
![image](https://github.com/arctheowl/snezhi-portfolio/assets/142297663/caa60021-aded-4fa1-859a-7321aecb8624)
Oxfordshire Manor showing as 3rd item but there are like 6 "Berkshires..."

**Comment by arctheowl** [comment]
Just looked at it abit more it looks to be sorting by date. Again we could add a priority field and label them all to be sorted.

**Comment by benseverett** [comment]
This has been added with #25
