### ISSUE TITLE
"Work" page link from menu causes fatal error

### ISSUE THREAD

**Issue by benseverett** [arctheowl/snezhi-portfolio#2]
Opening the "work" page from the top menu produces this error:

![image](https://github.com/arctheowl/snezhi-portfolio/assets/142297663/cbfc8b3f-d6ee-466d-9aab-0a1428831d09)

**Comment by arctheowl** [comment]
resolves in latest commit "8d19cfd..54e6c0d" - "Resolved work page crashing"
